cc_binary(
    name = "lrucache",
    srcs = ["lrucache.cc"],
)

cc_binary(
    name = "search",
    srcs = ["search.cc"],
)

cc_binary(
    name = "dfs",
    srcs = ["dfs.cc"],
    copts = ["-std=c++17"],
)
